name: Deploy microservice

on:
  push: 
    branches:
      - main
  workflow_dispatch: 

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      REGISTRY_UN: ${{ secrets.REGISTRY_UN }}
      REGISTRY_PW: ${{ secrets.REGISTRY_PW }}

    steps:
      
      # Checkout the code
      - uses: actions/checkout@v3

      #
      # Build Docker image
      #
      - name: Build Docker Image
        run: ./scripts/build-image.sh

      #
      # Push Docker image to Azure Container Registry
      #
      - name: Push Docker Image
        run: ./scripts/push-image.sh

      #
      # Set the kubeconfig
      #
      # Install Kubectl and deploy to Kubernetes
      #
      - name: Install Kubectl
        uses: azure/setup-kubectl@v1
        with:
            version: v1.24.2
      #
      # Deploy the microservice using Kubectl
      #
      - name: Deploy Microservice
        run: ./scripts/deploy.sh
